// Generated by https://quicktype.io

// Generated by https://quicktype.io

export interface Employee {
    department: Department;
    employeeId: string;
    firstName:  string;
    gender:     string;
    jobTitle:   JobTitle;
    lastName:   string;
    skill:      Skill[];
    title:      string;
    address:    string;
}

export interface Department {
    departmentCode: string;
    departmentName: string;
}

export interface JobTitle {
    jobTitleCode: string;
    jobTitleName: string;
    jobType:      string;
}

export interface Skill {
    employeeId: string;
    skillDesc:  string;
    skillId:    string;
    skillName:  string;
}


export interface Condition{
    departmentCode?:string;
    jobTitleCode?:string;
    jobType?:string;
    firstName?:string;
    lastName?:string;
    gender?:string;
}
